# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
